language: node_js

os:
  - linux
  - osx

node_js:
  - "8"

script: echo "Running tests against $(node -v) ..."

stages:
- test
- name: deploy
  if: branch = gh-pages

jobs:
  include:
  - stage: test
    script:
    - npm install
    - npm run lint
  - stage: deploy
    script:
    - npm install
    - npm build
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_TOKEN
      keep-history: true
      local-dir: public
      on:
        branch: master




