
language: node_js

os:
  - linux
  - osx

node_js:
  - "8"
before_script:
  - npm install

script:
 - npm run lint

before_deploy:
 - npm install
 - npm run build

stages:
- test
- name: deploy
  if: branch = gh-pages

jobs:
  include:
  - stage: test
    script:
      - npm run test
  - stage: deploy
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_TOKEN
      keep-history: true
      local-dir: public
      on:
        branch: master




