
language: node_js

os:
  - linux

node_js:
  - "8"
before_script:
  - npm install

script:
 - npm run lint

before_deploy:
 - npm install
 - npm run build

stages:
- test
- name: deploy

jobs:
  include:
  - stage: test
    script:
      - npm run test
  - deploy:
      provider: pages
      repo: wieslawmlynarski/mlynarski.cc
      skip-cleanup: true
      github-token: $GITHUB_TOKEN
      keep-history: true
      local-dir: public
      target-branch: master
      fqdn: mlynarski.cc
      on:
        branch: master-page
  - deploy:
      provider: pages
      repo: wieslawmlynarski/wieslaw.mlynarski.cc
      skip-cleanup: true
      github-token: $GITHUB_TOKEN
      keep-history: true
      local-dir: public
      fqdn: wieslaw.mlynarski.cc
      target-branch: master
      on:
        branch: master-page

